# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Baptiste Gaillard
email: baptiste.gaillard@gmail.com
description: >-
  Baptiste Gaillard's IT blog: Expert insights on Platform Engineering, DevOps, Cloud, SRE, and software architecture. Practical advice for modern IT challenges.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bgaillard.github.io"
twitter_username: jekyllrb
github_username:  bgaillard

# Build settings
theme: minima
minima:
  skin: dark
  show_excerpts: true
  social_links:
    - title: Baptiste Gaillard's LinkedIn profile
      icon: fa-linkedin
      url: "https://www.linkedin.com/in/baptistegaillard/"
    - title: Baptiste Gaillard's Github profile
      icon: fa-github
      url: "https://github.com/bgaillard"
    - title: "YmFwdGlzdGUuZ2FpbGxhcmRAZ21haWwuY29tCg=="
      icon: "fas fa-envelope"
      url: bWFpbHRvOmJhcHRpc3RlLmdhaWxsYXJkQGdtYWlsLmNvbQo=
      encrypted: true
    - title: "KzMzNjg1MTI4MTI2Cg=="
      icon: "fas fa-phone"
      url: "dGVsOiszMzY4NTEyODEyNgo="
      encrypted: true
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
